### ISSUE TITLE
Problems importing VLC

### ISSUE THREAD

**Issue by MaT1g3R** [EneApp/Ene#14]
<a href="https://github.com/MaT1g3R"><img src="https://avatars1.githubusercontent.com/u/15258494?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MaT1g3R](https://github.com/MaT1g3R)**
_Thursday Sep 06, 2018 at 19:32 GMT_
_Originally opened as https://github.com/MaT1g3R/ene/issues/14_

----

On systems without VLC installed the app crashes.

We should catch this error and disable VLC in settings instead.

**Comment by jsedge** [comment]
This was resolved with commit 6eda6aa0cc8878b9454b6e5d1ee0c636a33e3c68
LibVLC is not imported unless VLC is selected as the media player in settings
