### ISSUE TITLE
Make ENE respect desktop Qt theme

### ISSUE THREAD

**Issue by MaT1g3R** [EneApp/Ene#9]
<a href="https://github.com/MaT1g3R"><img src="https://avatars1.githubusercontent.com/u/15258494?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MaT1g3R](https://github.com/MaT1g3R)**
_Saturday Aug 11, 2018 at 00:13 GMT_
_Originally opened as https://github.com/MaT1g3R/ene/issues/9_

----

**Comment by jsedge** [comment]
Breeze is currently working on my PC after copying the breeze.so style from /usr/lib/qt/plugins/styles folder to the equivalent one in the PySide2 folder. Symlink would probably also fix it, not sure if this is something we can fix from Ene

**Comment by MaT1g3R** [comment]
https://www.reddit.com/r/kde/comments/ba1qrz/how_does_kde_apply_qt_styles_to_python_apps_using/

**Comment by jsedge** [comment]
Closing this one since it works if you're installing PySide2 from your package manager instead of using the pip package
